import { pgTable, uuid, text, integer, timestamp } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'
import { users } from '../../shared/user'

// QR Batches table - represents a batch of QR codes generated by staff
export const qrBatches = pgTable('qr_batches', {
  id: uuid('id').primaryKey().defaultRandom(),
  createdBy: uuid('created_by').notNull().references(() => users.id, { onDelete: 'cascade' }),
  prefix: text('prefix').notNull().default('TJW'),
  startFrom: integer('start_from').notNull(),    // e.g., 1
  count: integer('count').notNull(),             // e.g., 100
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})

// Relations are defined in relations.ts to avoid circular imports
